<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $mahabanks = array(
            array('id' => '1','bankid' => '1','bankcode' => 'UTIB','bankname' => 'Axis Bank','masterifsc' => 'UTIB0000003','url' => 'http://uat.mahagram.in/banklogo/axis_bank.png'),
            array('id' => '2','bankid' => '2','bankcode' => 'BARB','bankname' => 'Bank of Baroda','masterifsc' => 'BARB0AAMBUR','url' => 'http://uat.mahagram.in/banklogo/bank-of-baroda.png'),
            array('id' => '3','bankid' => '3','bankcode' => 'BKID','bankname' => 'Bank of India','masterifsc' => 'BKID0006005','url' => 'http://uat.mahagram.in/banklogo/BANK-OF-INDIA-LOGO.png'),
            array('id' => '4','bankid' => '4','bankcode' => 'CBIN','bankname' => 'Central Bank of India','masterifsc' => 'CBIN0280301','url' => 'http://uat.mahagram.in/banklogo/central-bank-of-india.jpg'),
            array('id' => '5','bankid' => '5','bankcode' => 'CITI','bankname' => 'Citibank','masterifsc' => 'CITI0000001','url' => 'http://uat.mahagram.in/banklogo/Citi-logo-880x660-487x365.png'),
            array('id' => '6','bankid' => '6','bankcode' => 'HDFC','bankname' => 'HDFC Bank','masterifsc' => 'HDFC0000001','url' => 'http://uat.mahagram.in/banklogo/hdfc_logo.png'),
            array('id' => '7','bankid' => '7','bankcode' => 'ICIC','bankname' => 'ICICI Bank','masterifsc' => 'ICIC0000001','url' => 'http://uat.mahagram.in/banklogo/ICICI-Logo.png'),
            array('id' => '8','bankid' => '8','bankcode' => 'IBKL','bankname' => 'IDBI Bank','masterifsc' => 'IBKL0000001','url' => 'http://uat.mahagram.in/banklogo/IDBI%20bank.png'),
            array('id' => '9','bankid' => '9','bankcode' => 'IDIB','bankname' => 'Indian Bank','masterifsc' => 'IDIB000A001','url' => 'http://uat.mahagram.in/banklogo/Indian%20Bank.jpg'),
            array('id' => '10','bankid' => '10','bankcode' => 'IOBA','bankname' => 'Indian Overseas Bank','masterifsc' => 'IOBA0000002','url' => 'http://uat.mahagram.in/banklogo/Indian%20Overseas%20Bank.png'),
            array('id' => '11','bankid' => '11','bankcode' => 'PUNB','bankname' => 'Punjab National Bank','masterifsc' => 'PUNB0455300','url' => 'http://uat.mahagram.in/banklogo/Punjab%20National%20Bank.png'),
            array('id' => '12','bankid' => '13','bankcode' => 'UBIN','bankname' => 'Union Bank of India','masterifsc' => 'UBIN0530018','url' => 'http://uat.mahagram.in/banklogo/union-bank-of-india.png'),
            array('id' => '13','bankid' => '14','bankcode' => 'UCBA','bankname' => 'UCO Bank','masterifsc' => 'UCBA0000001','url' => 'http://uat.mahagram.in/banklogo/UCO%20Bank.png'),
            array('id' => '14','bankid' => '16','bankcode' => 'YESB','bankname' => 'Yes Bank','masterifsc' => 'YESB0000001','url' => 'http://uat.mahagram.in/banklogo/Yes%20Bank.png'),
            array('id' => '15','bankid' => '17','bankcode' => 'BKDN','bankname' => 'Dena Bank','masterifsc' => 'BKDN0110011','url' => 'http://uat.mahagram.in/banklogo/Dena%20Bank.png'),
            array('id' => '16','bankid' => '18','bankcode' => 'ABHY','bankname' => 'Abhyudaya Co-Op Bank','masterifsc' => 'ABHY0065001','url' => 'http://uat.mahagram.in/banklogo/Abhyudaya%20Co-Op%20Bank.jpg'),
            array('id' => '17','bankid' => '19','bankcode' => 'ADCB','bankname' => 'Abu Dhabi Commercial Bank','masterifsc' => 'ADCB0000002','url' => 'http://uat.mahagram.in/banklogo/Abu%20Dhabi%20Commercial.jpg'),
            array('id' => '18','bankid' => '20','bankcode' => 'ALLA','bankname' => 'Allahabad Bank','masterifsc' => 'ALLA0210001','url' => 'http://uat.mahagram.in/banklogo/Allahabad%20Bank.jpg'),
            array('id' => '19','bankid' => '21','bankcode' => 'ANDB','bankname' => 'Andhra Bank','masterifsc' => 'ANDB0CG7001','url' => 'http://uat.mahagram.in/banklogo/Andhra%20Bank.jpg'),
            array('id' => '20','bankid' => '22','bankcode' => 'BOFA','bankname' => 'Bank of America','masterifsc' => 'BOFA0BG3978','url' => 'http://uat.mahagram.in/banklogo/Bank-Of-America-Logo-600x304.png'),
            array('id' => '21','bankid' => '23','bankcode' => 'BBKM','bankname' => 'Bank of Bahrain and Kuwait','masterifsc' => 'BBKM0000001','url' => 'http://uat.mahagram.in/banklogo/Bank%20of%20Bahrain%20and%20Kuwait.jpg'),
            array('id' => '22','bankid' => '24','bankcode' => 'BCEY','bankname' => 'Bank of Ceylon','masterifsc' => 'BCEY0000001','url' => 'http://uat.mahagram.in/banklogo/Bank%20of%20Ceylon.jpg'),
            array('id' => '23','bankid' => '25','bankcode' => 'MAHB','bankname' => 'Bank of Maharashtra','masterifsc' => 'MAHB0000001','url' => 'http://uat.mahagram.in/banklogo/Bank%20of%20Maharashtra.jpg'),
            array('id' => '24','bankid' => '26','bankcode' => 'BOTM','bankname' => 'Bank of Tokyo-Mitsubishi UFJ','masterifsc' => 'BOTM0BL3626','url' => 'http://uat.mahagram.in/banklogo/Bank%20of%20Tokyo-Mitsubishi.jpg'),
            array('id' => '25','bankid' => '27','bankcode' => 'BARC','bankname' => 'Barclays Bank','masterifsc' => 'BARC0INBB01','url' => 'http://uat.mahagram.in/banklogo/Barclays%20Bank.jpg'),
            array('id' => '26','bankid' => '28','bankcode' => 'BACB','bankname' => 'Bassein Catholic Co-Op Bank','masterifsc' => 'BACB0000001','url' => 'http://uat.mahagram.in/banklogo/Bassein%20Catholic%20Co-Op%20Bank.jpg'),
            array('id' => '27','bankid' => '29','bankcode' => 'BNPA','bankname' => 'BNP Paribas','masterifsc' => 'BNPA0009008','url' => 'http://uat.mahagram.in/banklogo/BNP%20Paribas.png'),
            array('id' => '28','bankid' => '30','bankcode' => 'CNRB','bankname' => 'Canara Bank','masterifsc' => 'CNRB0000002','url' => 'http://uat.mahagram.in/banklogo/Canara%20Bank.png'),
            array('id' => '29','bankid' => '32','bankcode' => 'CSBK','bankname' => 'Catholic Syrian Bank','masterifsc' => 'CSBK0000001','url' => 'http://uat.mahagram.in/banklogo/Catholic%20Syrian%20Bank.png'),
            array('id' => '30','bankid' => '33','bankcode' => 'CTCB','bankname' => 'Chinatrust Commercial Bank','masterifsc' => 'CTCB0000001','url' => 'http://uat.mahagram.in/banklogo/Chinatrust%20Commercial%20Bank.png'),
            array('id' => '31','bankid' => '34','bankcode' => 'CCBL','bankname' => 'Citizen Credit Co-Op Bank','masterifsc' => 'CCBL0209002','url' => 'http://uat.mahagram.in/banklogo/Citizen Credit Co-Op Bank.png'),
            array('id' => '32','bankid' => '35','bankcode' => 'CIUB','bankname' => 'City Union Bank','masterifsc' => 'CIUB0000001','url' => 'http://uat.mahagram.in/banklogo/City%20Union%20Bank.png'),
            array('id' => '33','bankid' => '37','bankcode' => 'CORP','bankname' => 'Corporation Bank','masterifsc' => 'CORP0000001','url' => 'http://uat.mahagram.in/banklogo/Corporation%20Bank.jpg'),
            array('id' => '34','bankid' => '38','bankcode' => 'CRLY','bankname' => 'Credit Agricole Corp N Investment Bank','masterifsc' => 'CRLY0000002','url' => 'http://uat.mahagram.in/banklogo/Credit%20Agricole%20Corp%20N%20Investment%20Bank.png'),
            array('id' => '35','bankid' => '39','bankcode' => 'DBSS','bankname' => 'DBS Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/DBS%20Bank.png'),
            array('id' => '36','bankid' => '41','bankcode' => 'DEUT','bankname' => 'Deutsche Bank AG','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Deutsche%20Bank%20AG.jpg'),
            array('id' => '37','bankid' => '42','bankcode' => 'DCBL','bankname' => 'Development Credit Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Development%20Credit%20Bank.png'),
            array('id' => '38','bankid' => '43','bankcode' => 'DLXB','bankname' => 'Dhanlaxmi Bank','masterifsc' => 'DLXB0000001','url' => 'http://uat.mahagram.in/banklogo/Dhanlaxmi%20Bank.jpg'),
            array('id' => '39','bankid' => '44','bankcode' => 'DICG','bankname' => 'DICGC','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/DICGC.jpg'),
            array('id' => '40','bankid' => '45','bankcode' => 'DNSB','bankname' => 'Dombivli Nagari Sahakari Bank','masterifsc' => 'DNSB0000002','url' => 'http://uat.mahagram.in/banklogo/Dombivli%20Nagari%20Sahakari%20Bank.jpg'),
            array('id' => '41','bankid' => '46','bankcode' => 'FIRN','bankname' => 'Firstrand Bank','masterifsc' => 'FIRN0000001','url' => 'http://uat.mahagram.in/banklogo/Firstrand%20Bank.jpg'),
            array('id' => '42','bankid' => '47','bankcode' => 'HSBC','bankname' => 'HSBC','masterifsc' => 'HSBC0110002','url' => 'http://uat.mahagram.in/banklogo/HSBC-Bank-USA-Logo.jpg'),
            array('id' => '43','bankid' => '48','bankcode' => 'INDB','bankname' => 'IndusInd Bank','masterifsc' => 'INDB0000001','url' => 'http://uat.mahagram.in/banklogo/IndusInd%20Bank.png'),
            array('id' => '44','bankid' => '49','bankcode' => 'VYSA','bankname' => 'ING Vysya Bank','masterifsc' => 'VYSA0001000','url' => 'http://uat.mahagram.in/banklogo/ING-Vysya-Bank-Logo.png'),
            array('id' => '45','bankid' => '50','bankcode' => 'JSBL','bankname' => 'Janakalyan Sahakari Bank','masterifsc' => 'JSBL0000002','url' => 'http://uat.mahagram.in/banklogo/Janakalyan%20Sahakari%20Bank.png'),
            array('id' => '46','bankid' => '51','bankcode' => 'JSBP','bankname' => 'Janata Sahakari Bank,Pune','masterifsc' => 'JSBP0000002','url' => 'http://uat.mahagram.in/banklogo/Janata%20Sahakari%20Bank,Pune.jpg'),
            array('id' => '47','bankid' => '52','bankcode' => 'CHAS','bankname' => 'JP Morgan Chase Bank','masterifsc' => 'CHAS0INBX01','url' => 'http://uat.mahagram.in/banklogo/JP%20Morgan%20Chase%20Bank.png'),
            array('id' => '48','bankid' => '53','bankcode' => 'KCBL','bankname' => 'Kapole Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Kapole%20Co-Op%20Bank.jpg'),
            array('id' => '49','bankid' => '54','bankcode' => 'KARB','bankname' => 'Karnataka Bank','masterifsc' => 'KARB0000001','url' => 'http://uat.mahagram.in/banklogo/Karnataka%20Bank.png'),
            array('id' => '50','bankid' => '55','bankcode' => 'KVBL','bankname' => 'Karur Vysya Bank','masterifsc' => 'KVBL0001101','url' => 'http://uat.mahagram.in/banklogo/Karur%20Vysya%20Bank.jpg'),
            array('id' => '51','bankid' => '56','bankcode' => 'KKBK','bankname' => 'Kotak Mahindra Bank','masterifsc' => 'KKBK0PCBL04','url' => 'http://uat.mahagram.in/banklogo/Kotak-Mahindra-Bank-Logo.png'),
            array('id' => '52','bankid' => '57','bankcode' => 'MCBL','bankname' => 'Mahanagar Co-Op Bank','masterifsc' => 'KKBK0MCUB01','url' => 'http://uat.mahagram.in/banklogo/Mahanagar%20Co-Op%20Bank.jpg'),
            array('id' => '53','bankid' => '58','bankcode' => 'MSCI','bankname' => 'Maharashtra State Co-Op Bank','masterifsc' => 'MSCI0082002','url' => 'http://uat.mahagram.in/banklogo/Bank%20of%20Maharashtra.jpg'),
            array('id' => '54','bankid' => '59','bankcode' => 'MSHQ','bankname' => 'Mashreq Bank PSC','masterifsc' => 'MSHQ0000001','url' => 'http://uat.mahagram.in/banklogo/Mashreq%20Bank%20PSC.jpg'),
            array('id' => '55','bankid' => '60','bankcode' => 'MHCB','bankname' => 'Mizuho Corporate Bank','masterifsc' => 'MHCB0000002','url' => 'http://uat.mahagram.in/banklogo/Mizuho%20Corporate%20Bank.jpg'),
            array('id' => '56','bankid' => '61','bankcode' => 'NICB','bankname' => 'New India Co-Op Bank','masterifsc' => 'NICB0000003','url' => 'http://uat.mahagram.in/banklogo/New%20India%20Co-Op%20Bank.jpg'),
            array('id' => '57','bankid' => '62','bankcode' => 'NKGS','bankname' => 'NKGSB Co-Op Bank','masterifsc' => 'NKGS0000001','url' => 'http://uat.mahagram.in/banklogo/NKGSB%20Co-Op%20Bank.png'),
            array('id' => '58','bankid' => '63','bankcode' => 'NNSB','bankname' => 'Nutan Nagarik Sahakari Bank','masterifsc' => 'NNSB0128002','url' => 'http://uat.mahagram.in/banklogo/Nutan%20Nagarik%20Sahakari%20Bank.jpg'),
            array('id' => '59','bankid' => '64','bankcode' => 'OIBA','bankname' => 'Oman International Bank Saog','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Oman%20International%20Bank%20Saog.png'),
            array('id' => '60','bankid' => '65','bankcode' => 'ORBC','bankname' => 'Oriental Bank of Commerce','masterifsc' => 'ORBC0000023','url' => 'http://uat.mahagram.in/banklogo/Oriental%20Bank%20of%20Commerce.png'),
            array('id' => '61','bankid' => '66','bankcode' => 'PJSB','bankname' => 'Parsik Janata Sahakari Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Parsik%20Janata%20Sahakari%20Bank.jpg'),
            array('id' => '62','bankid' => '67','bankcode' => 'PMCB','bankname' => 'Punjab and Maharashtra Co-Op Bank','masterifsc' => 'PMCB0000002','url' => 'http://uat.mahagram.in/banklogo/Punjab%20and%20Maharashtra%20Co-Op%20Bank.png'),
            array('id' => '63','bankid' => '68','bankcode' => 'PSIB','bankname' => 'Punjab and Sind Bank','masterifsc' => 'PSIB0000001','url' => 'http://uat.mahagram.in/banklogo/Punjab%20and%20Sind%20Bank.png'),
            array('id' => '64','bankid' => '69','bankcode' => 'RNSB','bankname' => 'Rajkot Nagarik Sahakari Bank','masterifsc' => 'RNSB0000001','url' => 'http://uat.mahagram.in/banklogo/Rajkot%20Nagarik%20Sahakari%20Bank.jpg'),
            array('id' => '65','bankid' => '70','bankcode' => 'RBIS','bankname' => 'Reserve Bank of India','masterifsc' => 'RBIS0AHPA01','url' => 'http://uat.mahagram.in/banklogo/Reserve%20Bank%20of%20India.png'),
            array('id' => '66','bankid' => '71','bankcode' => 'SHBK','bankname' => 'Shinhan Bank','masterifsc' => 'SHBK0000001','url' => 'http://uat.mahagram.in/banklogo/Shinhan%20Bank.jpg'),
            array('id' => '67','bankid' => '72','bankcode' => 'SOGE','bankname' => 'Societe Generale','masterifsc' => 'SOGE0INBB01','url' => 'http://uat.mahagram.in/banklogo/Societe%20Generale.png'),
            array('id' => '68','bankid' => '73','bankcode' => 'SIBL','bankname' => 'South Indian Bank','masterifsc' => 'SIBL0000001','url' => 'http://uat.mahagram.in/banklogo/South%20Indian%20Bank.png'),
            array('id' => '69','bankid' => '74','bankcode' => 'SCBL','bankname' => 'Standard Chartered Bank','masterifsc' => 'SCBL0036001','url' => 'http://uat.mahagram.in/banklogo/Standard%20Chartered%20Bank.jpg'),
            array('id' => '70','bankid' => '75','bankcode' => 'SBHY','bankname' => 'State Bank of Hyderabad','masterifsc' => 'SBHY0020001','url' => 'http://uat.mahagram.in/banklogo/State%20Bank%20of%20Hyderabad.png'),
            array('id' => '71','bankid' => '76','bankcode' => 'STCB','bankname' => 'State Bank of Mauritius','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/State%20Bank%20of%20Mauritius.png'),
            array('id' => '72','bankid' => '77','bankcode' => 'SBMY','bankname' => 'State Bank of Mysore','masterifsc' => 'SBMY0040001','url' => 'http://uat.mahagram.in/banklogo/State%20Bank%20of%20Mysore.png'),
            array('id' => '73','bankid' => '78','bankcode' => 'SBTR','bankname' => 'State Bank of Travancore','masterifsc' => 'SBTR0000001','url' => 'http://uat.mahagram.in/banklogo/State%20Bank%20of%20Travancore.png'),
            array('id' => '74','bankid' => '81','bankcode' => 'TMBL','bankname' => 'Tamilnad Mercantile Bank','masterifsc' => 'TMBL0000001','url' => 'http://uat.mahagram.in/banklogo/Tamilnad%20Mercantile%20Bank.png'),
            array('id' => '75','bankid' => '84','bankcode' => 'BCBM','bankname' => 'Bharat Co-Op Bank, Mumbai','masterifsc' => 'BCBM0000001','url' => 'http://uat.mahagram.in/banklogo/Bharat%20Co-Op%20Bank.png'),
            array('id' => '76','bankid' => '85','bankcode' => 'COSB','bankname' => 'Cosmos Co-Op Bank','masterifsc' => 'COSB0000001','url' => 'http://uat.mahagram.in/banklogo/Cosmos%20Co-Op%20Bank.png'),
            array('id' => '77','bankid' => '86','bankcode' => 'FDRL','bankname' => 'The Federal Bank Ltd','masterifsc' => 'FDRL0000001','url' => 'http://uat.mahagram.in/banklogo/The%20Federal%20Bank%20Ltd.jpg'),
            array('id' => '78','bankid' => '87','bankcode' => 'GBCB','bankname' => 'Greater Bombay Co-Op Bank','masterifsc' => 'GBCB0000001','url' => 'http://uat.mahagram.in/banklogo/Greater%20Bombay%20Co-Op%20Bank.png'),
            array('id' => '79','bankid' => '88','bankcode' => 'JAKA','bankname' => 'Jammu and Kashmir Bank','masterifsc' => 'JAKA0AALLAH','url' => 'http://uat.mahagram.in/banklogo/Jammu%20and%20Kashmir%20Bank.png'),
            array('id' => '80','bankid' => '89','bankcode' => 'KCCB','bankname' => 'Kalupur Commercial Co-Op Bank','masterifsc' => 'KCCB0AKL045','url' => 'http://uat.mahagram.in/banklogo/Kalupur%20Commercial%20Co-Op%20Bank.png'),
            array('id' => '81','bankid' => '90','bankcode' => 'KSBC','bankname' => 'Karnataka State Apex Co-Op','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Karnataka%20State%20Apex%20Co-Op.png'),
            array('id' => '82','bankid' => '91','bankcode' => 'KJSB','bankname' => 'Kalyan Janata Sahakari Bank','masterifsc' => 'KJSB0000002','url' => 'http://uat.mahagram.in/banklogo/Kalyan%20Janata%20Sahakari%20Bank.jpg'),
            array('id' => '83','bankid' => '92','bankcode' => 'LAVB','bankname' => 'Lakshmi Vilas Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Lakshmi%20Vilas%20Bank.jpg'),
            array('id' => '84','bankid' => '93','bankcode' => 'MSNU','bankname' => 'Mehsana Urban Co-Op Bank','masterifsc' => 'MSNU0000001','url' => 'http://uat.mahagram.in/banklogo/Mehsana%20Urban%20Co-Op%20Bank.jpg'),
            array('id' => '85','bankid' => '94','bankcode' => 'NTBL','bankname' => 'Nainital Bank','masterifsc' => 'NTBL0AGR072','url' => 'http://uat.mahagram.in/banklogo/Nainital-Bank-Logo.jpg'),
            array('id' => '86','bankid' => '95','bankcode' => 'RATN','bankname' => 'Ratnakar Bank','masterifsc' => 'RATN0000013','url' => 'http://uat.mahagram.in/banklogo/ratnakar-bank.png'),
            array('id' => '87','bankid' => '96','bankcode' => 'ABNA','bankname' => 'Royal Bank of Scotland','masterifsc' => 'ABNA0000001','url' => 'http://uat.mahagram.in/banklogo/Royal%20Bank%20of%20Scotland.png'),
            array('id' => '88','bankid' => '97','bankcode' => 'SRCB','bankname' => 'Saraswat Co-Op Bank','masterifsc' => 'SRCB0000001','url' => 'http://uat.mahagram.in/banklogo/Saraswat%20Co-Op%20Bank.png'),
            array('id' => '89','bankid' => '98','bankcode' => 'SVCB','bankname' => 'The Shamrao Vithal Co-Operative Bank','masterifsc' => 'SVCB0000001','url' => 'http://uat.mahagram.in/banklogo/The%20Shamrao%20Vithal%20Co-Operative.png'),
            array('id' => '90','bankid' => '99','bankcode' => 'SPCB','bankname' => 'Surat Peoples Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Surat%20Peoples%20Co-Op%20Bank.png'),
            array('id' => '91','bankid' => '100','bankcode' => 'TJSB','bankname' => 'Thane Janata Sahakari Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Thane%20Janata%20Sahakari%20Bank.jpg'),
            array('id' => '92','bankid' => '101','bankcode' => 'TNSC','bankname' => 'Tamilnadu State Apex Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/TamilNadu%20Bank.jpg'),
            array('id' => '93','bankid' => '102','bankcode' => 'WBSC','bankname' => 'West Bengal State Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/west%20bangal%20bank.jpg'),
            array('id' => '94','bankid' => '103','bankcode' => 'VIJB','bankname' => 'Vijaya Bank','masterifsc' => 'VIJB0001001','url' => 'http://uat.mahagram.in/banklogo/vijaya-bank.png'),
            array('id' => '95','bankid' => '108','bankcode' => 'SBIN','bankname' => 'State Bank of India','masterifsc' => 'SBIN0000001','url' => 'http://uat.mahagram.in/banklogo/SBI.png'),
            array('id' => '96','bankid' => '109','bankcode' => 'APMC','bankname' => 'AP Mahesh Co-Op Urban Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Ap%20Mahesh%20bank.jpg'),
            array('id' => '97','bankid' => '110','bankcode' => 'KUCB','bankname' => 'Karad Urban Co-Op Bank','masterifsc' => 'KUCB0488000','url' => 'http://uat.mahagram.in/banklogo/Karad-urban-co-op-bank.jpg'),
            array('id' => '98','bankid' => '111','bankcode' => 'KSCB','bankname' => 'Karnataka State Co-Op Apex Bank, Bangalore','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Karnataka%20State%20Apex%20Co-Op.png'),
            array('id' => '99','bankid' => '112','bankcode' => 'NMCB','bankname' => 'Nashik Merchants Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Nasik-merchants-co-op-bank.jpg'),
            array('id' => '100','bankid' => '113','bankcode' => 'UBSW','bankname' => 'UBS AG','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/UBS%20bank.jpg'),
            array('id' => '101','bankid' => '114','bankcode' => 'UTBI','bankname' => 'United Bank of India','masterifsc' => 'UTBI0AAD648','url' => 'http://uat.mahagram.in/banklogo/United%20Bank%20of%20India.jpg'),
            array('id' => '102','bankid' => '115','bankcode' => 'KANG','bankname' => 'Kangra Co-Op Bank','masterifsc' => 'KANG0000001','url' => 'http://uat.mahagram.in/banklogo/Kangra%20bank.jpg'),
            array('id' => '103','bankid' => '116','bankcode' => 'KACE','bankname' => 'Kangra Central Co-Op Bank','masterifsc' => 'KACE0000001','url' => 'http://uat.mahagram.in/banklogo/Kangra%20central.jpg'),
            array('id' => '104','bankid' => '117','bankcode' => 'PRTH','bankname' => 'Prathama Bank','masterifsc' => 'PRTH0000001','url' => 'http://uat.mahagram.in/banklogo/Prathama%20bank.jpg'),
            array('id' => '105','bankid' => '119','bankcode' => 'ACGG','bankname' => 'Chaitanya Godavari Grameena Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Chaitanya-Godavari-Grameena-Bank-CGGB.jpg'),
            array('id' => '106','bankid' => '120','bankcode' => 'ALLG','bankname' => 'Allahabad UP Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/allahabad%20gramin%20bank.jpg'),
            array('id' => '107','bankid' => '121','bankcode' => 'ANDG','bankname' => 'Rushikulya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Rushikulya-gramya-bank.jpg'),
            array('id' => '108','bankid' => '122','bankcode' => 'ASGB','bankname' => 'Sharda Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/sharda-gramin-bank.jpg'),
            array('id' => '109','bankid' => '123','bankcode' => 'BARG','bankname' => 'Nainital Almora Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Nainital%20almora%20bank.jpg'),
            array('id' => '110','bankid' => '124','bankcode' => 'BARR','bankname' => 'Baroda Rajasthan Kshetriya Gramin Bank','masterifsc' => 'BARB0BRGBXX','url' => 'http://uat.mahagram.in/banklogo/Baroda%20rajasthan%20bank.jpg'),
            array('id' => '111','bankid' => '125','bankcode' => 'BARU','bankname' => 'Baroda Uttar Pradesh Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Baroda%20uttar%20pradesh.jpg'),
            array('id' => '112','bankid' => '126','bankcode' => 'BGGB','bankname' => 'Baroda Gujarat Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Baroda-gujarat-gramin-bank.jpg'),
            array('id' => '113','bankid' => '127','bankcode' => 'BJDG','bankname' => 'Jhabua Dhar Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Jhabua%20dar%20kshetriya%20bank.png'),
            array('id' => '114','bankid' => '128','bankcode' => 'BKDD','bankname' => 'Dena Gujarat Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Dena%20gujrat%20bank.png'),
            array('id' => '115','bankid' => '129','bankcode' => 'BKDR','bankname' => 'Durg Rajnandgaon Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Durg-rajnandgaon-gramin-bank.jpg'),
            array('id' => '116','bankid' => '130','bankcode' => 'BKIB','bankname' => 'Baitarani Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Baitarni_Gramin_bank.png'),
            array('id' => '117','bankid' => '131','bankcode' => 'BKIG','bankname' => 'Aryavart Gramin Bank','masterifsc' => 'BKID0ARYAGB','url' => 'http://uat.mahagram.in/banklogo/Gramin-Bank-of-Aryavart.jpg'),
            array('id' => '118','bankid' => '133','bankcode' => 'BWKG','bankname' => 'Wainganga Krishna Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/wainganga%20krishna%20gramin%20bank.jpg'),
            array('id' => '119','bankid' => '134','bankcode' => 'CBBB','bankname' => 'Uttar Bihar Gramin Bank','masterifsc' => 'CBIN0R10001','url' => 'http://uat.mahagram.in/banklogo/Uttar-Bihar-Gramin-Bank.jpg'),
            array('id' => '120','bankid' => '135','bankcode' => 'CBIG','bankname' => 'Ballia Etawah Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Baliya%20itawa%20gramin%20bank.jpg'),
            array('id' => '121','bankid' => '136','bankcode' => 'CBIH','bankname' => 'Hadoti Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => NULL),
            array('id' => '122','bankid' => '137','bankcode' => 'CKGB','bankname' => 'Surguja Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Surguja%20gramin%20bank.jpg'),
            array('id' => '123','bankid' => '138','bankcode' => 'CMGB','bankname' => 'South Malabar Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/South-Malabar-Gramin-Bank.png'),
            array('id' => '124','bankid' => '139','bankcode' => 'CORG','bankname' => 'Chickmangalur Kodagu Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/chikmagalur-kodagu-grameena-bank.jpg'),
            array('id' => '125','bankid' => '140','bankcode' => 'CPGB','bankname' => 'Pragathi Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Pragathi%20Krishna%20Gramin%20Bank.jpg'),
            array('id' => '126','bankid' => '141','bankcode' => 'CSGB','bankname' => 'Shreyas Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Shreyas-Gramin-Bank.png'),
            array('id' => '127','bankid' => '142','bankcode' => 'CSUG','bankname' => 'Satpura Narmada Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/satpura-narmada-kshetriya-gramin-bank.jpg'),
            array('id' => '128','bankid' => '143','bankcode' => 'CUKG','bankname' => 'Uttar Banga Kshetriya Gramin Bank','masterifsc' => 'CBIN0R40012','url' => 'http://uat.mahagram.in/banklogo/Uttar banga kshetriya gramin bank.jpg'),
            array('id' => '129','bankid' => '144','bankcode' => 'CVAG','bankname' => 'Vidharbha Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Vidharbha Kshetriya Gramin Bank.jpg'),
            array('id' => '130','bankid' => '145','bankcode' => 'FBIG','bankname' => 'Madhya Bharat Gramin Bank','masterifsc' => 'SBIN0RRMBGB','url' => 'http://uat.mahagram.in/banklogo/madhya-bharat-gramin-bank.jpg'),
            array('id' => '131','bankid' => '146','bankcode' => 'GGBK','bankname' => 'Gurgaon Gramin Bank','masterifsc' => 'GGBK0000001','url' => 'http://uat.mahagram.in/banklogo/Gurgaon-Gramin-Bank.png'),
            array('id' => '132','bankid' => '147','bankcode' => 'HDFG','bankname' => 'Malwa Gramin Bank','masterifsc' => 'STBP0RRMLGB','url' => 'http://uat.mahagram.in/banklogo/malwa%20Gramin%20bank.jpg'),
            array('id' => '133','bankid' => '148','bankcode' => 'ICIG','bankname' => 'Mewar Anchalik Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Mewar-Aanchalik-Gramin-Bank.jpg'),
            array('id' => '134','bankid' => '149','bankcode' => 'IDIG','bankname' => 'Pallavan Grama Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Pallavan%20gramin%20bank.jpg'),
            array('id' => '135','bankid' => '150','bankcode' => 'INGB','bankname' => 'Neelachal Gramya Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Neelachal-Gramya-Bank.jpg'),
            array('id' => '136','bankid' => '151','bankcode' => 'IOBG','bankname' => 'Pandyan Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/pandian-grama-bank.jpg'),
            array('id' => '137','bankid' => '152','bankcode' => 'IPBG','bankname' => 'Puduvai Bharathiar Grama Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Puduvai%20Bharathair%20grama%20bank.jpg'),
            array('id' => '138','bankid' => '153','bankcode' => 'JAKG','bankname' => 'J&K Grameen Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/J&K%20Grameen%20bank.jpg'),
            array('id' => '139','bankid' => '154','bankcode' => 'MAHG','bankname' => 'Maharashtra Gramin Bank','masterifsc' => 'MAHB0RRBMGB','url' => 'http://uat.mahagram.in/banklogo/Maharashtra-Gramin-Bank.jpg'),
            array('id' => '140','bankid' => '156','bankcode' => 'PRGB','bankname' => 'Rajasthan Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Rajasthan%20Gramin%20Bank.jpg'),
            array('id' => '141','bankid' => '157','bankcode' => 'PSGB','bankname' => 'Sarva UP Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Sarva%20up%20gramin%20bank.jpg'),
            array('id' => '142','bankid' => '158','bankcode' => 'PSIG','bankname' => 'Sutlej Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Sutlej%20gramin%20bank.jpg'),
            array('id' => '143','bankid' => '159','bankcode' => 'PUHG','bankname' => 'Himachal Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Himachal%20Gramin%20Bank.jpg'),
            array('id' => '144','bankid' => '160','bankcode' => 'PUNG','bankname' => 'Madhya Bihar Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Madhya%20Bihar%20Gramin%20Bank.jpg'),
            array('id' => '145','bankid' => '161','bankcode' => 'PUNH','bankname' => 'Sarva Haryana Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Sarva-Haryana-Gramin-Bank.jpg'),
            array('id' => '146','bankid' => '162','bankcode' => 'SAPG','bankname' => 'Andhra Pradesh Grameena Vikas Bank','masterifsc' => 'SBIN0RRAPGB','url' => 'http://uat.mahagram.in/banklogo/Andhra-Pradesh-Grameena-Vikas-Bank.jpg'),
            array('id' => '147','bankid' => '163','bankcode' => 'SBAP','bankname' => 'Arunachal Pradesh Rural Bank','masterifsc' => 'SBIN0RRARGB','url' => 'http://uat.mahagram.in/banklogo/Arunachal-Pradesh-Rural-Bank.jpg'),
            array('id' => '148','bankid' => '164','bankcode' => 'SBBG','bankname' => 'MG Baroda Gramin Bank','masterifsc' => 'NULL','url' => NULL),
            array('id' => '149','bankid' => '165','bankcode' => 'SBHG','bankname' => 'Telangana Grameena Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/telangana-grameena-bank.jpg'),
            array('id' => '150','bankid' => '166','bankcode' => 'SBIC','bankname' => 'Chhattisgarh Gramin Bank','masterifsc' => 'SBIN0RRCHGB','url' => 'http://uat.mahagram.in/banklogo/Chahattisgarh%20gramin%20bank.png'),
            array('id' => '151','bankid' => '167','bankcode' => 'SBIE','bankname' => 'Ellaqui Dehati Bank','masterifsc' => 'SBIN0RRELGB','url' => 'http://uat.mahagram.in/banklogo/Ellaqui%20dehati%20bank.jpg'),
            array('id' => '152','bankid' => '168','bankcode' => 'SBIG','bankname' => 'Mizoram Rural Bank','masterifsc' => 'SBIN0RRMIGB','url' => 'http://uat.mahagram.in/banklogo/Mijoram%20rura%20bank.jpg'),
            array('id' => '153','bankid' => '169','bankcode' => 'SBIJ','bankname' => 'Jharkhand Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Jharkhand-Gramin-Bank.png'),
            array('id' => '154','bankid' => '170','bankcode' => 'SBMG','bankname' => 'Kaveri Grameena Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Kaveri-Grameena-Bank.jpg'),
            array('id' => '155','bankid' => '171','bankcode' => 'SBOG','bankname' => 'Vidisha Bhopal Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/vidisha-bhopal-kshetriya-gramin-bank.jpg'),
            array('id' => '156','bankid' => '172','bankcode' => 'SKRG','bankname' => 'Krishna Gramin Bank','masterifsc' => 'PKGB0010500','url' => 'http://uat.mahagram.in/banklogo/Pragathi-Krishna-Gramin-Bank.jpg'),
            array('id' => '157','bankid' => '173','bankcode' => 'SLDR','bankname' => 'Langpi Dehangi Rural Bank','masterifsc' => 'SBIN0RRLDGB','url' => 'http://uat.mahagram.in/banklogo/langpi-dehangi-rural-bank.jpg'),
            array('id' => '158','bankid' => '174','bankcode' => 'SMEG','bankname' => 'Meghalaya Rural Bank','masterifsc' => 'SBIN0RRMEGB','url' => 'http://uat.mahagram.in/banklogo/Meghalaya-Rural-Bank.jpg'),
            array('id' => '159','bankid' => '176','bankcode' => 'SPGB','bankname' => 'Parvatiya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Parvatiya-Gramin-Bank.jpg'),
            array('id' => '160','bankid' => '177','bankcode' => 'SRGB','bankname' => 'Purvanchal Gramin Bank','masterifsc' => 'SBIN0RRPUGB','url' => 'http://uat.mahagram.in/banklogo/Puravachal%20gramin%20bank.jpg'),
            array('id' => '161','bankid' => '179','bankcode' => 'SSGB','bankname' => 'Saurashtra Gramin Bank','masterifsc' => 'SBIN0RRSRGB','url' => 'http://uat.mahagram.in/banklogo/Saurashtra%20Gramin%20Bank.png'),
            array('id' => '162','bankid' => '180','bankcode' => 'SSKG','bankname' => 'Samastipur Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Samastipur%20Kshetriya%20Gramin%20Bank.png'),
            array('id' => '163','bankid' => '181','bankcode' => 'SUTG','bankname' => 'Uttarakhand Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Uttarakhand%20Gramin%20Bank.png'),
            array('id' => '164','bankid' => '182','bankcode' => 'SUUG','bankname' => 'Utkal Gramya Bank','masterifsc' => 'SBIN0RRUKGB','url' => 'http://uat.mahagram.in/banklogo/Utkal%20Gramya%20Bank.jpg'),
            array('id' => '165','bankid' => '184','bankcode' => 'KVGB','bankname' => 'Karnataka Vikas Grameena Bank','masterifsc' => 'KVGB0000001','url' => 'http://uat.mahagram.in/banklogo/Karnataka%20Vikas%20Grameena%20Bank.jpg'),
            array('id' => '166','bankid' => '185','bankcode' => 'APGB','bankname' => 'Andhra Pragathi Grameena Bank','masterifsc' => 'APGB0000001','url' => 'http://uat.mahagram.in/banklogo/Andhra%20Pragathi%20Grameena%20Bank.jpg'),
            array('id' => '167','bankid' => '186','bankcode' => 'SYNM','bankname' => 'North Malabar Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/North Malabar Gramin Bank.jpg'),
            array('id' => '168','bankid' => '187','bankcode' => 'UASG','bankname' => 'Assam Gramin Vikash Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Assam%20Gramin%20Vikash%20Bank.png'),
            array('id' => '169','bankid' => '188','bankcode' => 'UBKG','bankname' => 'Kashi Gomati Samyut Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Kashi%20Gomati%20Samyut%20Gramin%20Bank.jpg'),
            array('id' => '170','bankid' => '189','bankcode' => 'UCBG','bankname' => 'Mahakaushal Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Mahakaushal%20Kshetriya%20Gramin.jpg'),
            array('id' => '171','bankid' => '190','bankcode' => 'UCBK','bankname' => 'Bihar Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Mahakaushal%20Kshetriya%20Gramin.jpg'),
            array('id' => '172','bankid' => '191','bankcode' => 'UCKG','bankname' => 'Kalinga Gramya Bank','masterifsc' => 'NULL','url' => NULL),
            array('id' => '173','bankid' => '192','bankcode' => 'UJTG','bankname' => 'Jaipur Thar Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Jaipur%20Thar%20Gramin%20Bank.jpg'),
            array('id' => '174','bankid' => '193','bankcode' => 'UPBG','bankname' => 'Paschim Banga Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Paschim%20Banga%20Gramin%20Bank.png'),
            array('id' => '175','bankid' => '194','bankcode' => 'URSG','bankname' => 'Rewa-Sidhi Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Rewa-Sidhi%20Gramin%20Bank.png'),
            array('id' => '176','bankid' => '195','bankcode' => 'UTBB','bankname' => 'Bangiya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Bangiya%20Gramin%20Bank.jpg'),
            array('id' => '177','bankid' => '196','bankcode' => 'UTBG','bankname' => 'Manipur Rural ANK','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Manipur%20Rural%20ANK.png'),
            array('id' => '178','bankid' => '197','bankcode' => 'UTGB','bankname' => 'Tripura Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Tripura%20Gramin%20Bank.png'),
            array('id' => '179','bankid' => '198','bankcode' => 'VIJG','bankname' => 'Visveshwaraya Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Visveshwaraya%20Gramin%20Bank.jpg'),
            array('id' => '180','bankid' => '199','bankcode' => 'SBCG','bankname' => 'Swarna Bharat Trust Cyber Grameen','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Swarna%20Bharat%20Trust%20Cyber%20Grameen.png'),
            array('id' => '181','bankid' => '200','bankcode' => 'NMGB','bankname' => 'NEFT Malwa Gramin Bank','masterifsc' => 'STBP0RRMLGB','url' => 'http://uat.mahagram.in/banklogo/NEFT%20Malwa%20Gramin%20Bank.jpg'),
            array('id' => '182','bankid' => '201','bankcode' => 'ABCC','bankname' => 'ABN Amro Bank Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/ABN%20Amro%20Bank%20Credit%20Card.png'),
            array('id' => '183','bankid' => '202','bankcode' => 'BACC','bankname' => 'Barclays Credit Card','masterifsc' => 'BARC0INBB01','url' => 'http://uat.mahagram.in/banklogo/Barclays%20Credit%20Card.png'),
            array('id' => '184','bankid' => '203','bankcode' => 'CICC','bankname' => 'Citibank Credit Card','masterifsc' => 'CITI0000001','url' => 'http://uat.mahagram.in/banklogo/Citi-logo-880x660-487x365.png'),
            array('id' => '185','bankid' => '204','bankcode' => 'HDCC','bankname' => 'HDFC Bank Credit Card','masterifsc' => 'HDFC0000001','url' => 'http://uat.mahagram.in/banklogo/hdfc_logo.png'),
            array('id' => '186','bankid' => '205','bankcode' => 'HSCC','bankname' => 'HSBC Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/HSBC-Bank-USA-Logo.jpg'),
            array('id' => '187','bankid' => '206','bankcode' => 'ICCC','bankname' => 'ICICI Bank Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/ICICI-Logo.png'),
            array('id' => '188','bankid' => '207','bankcode' => 'KKCC','bankname' => 'Kotak Mahindra Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Kotak-Mahindra-Bank-Logo.png'),
            array('id' => '189','bankid' => '208','bankcode' => 'SBCC','bankname' => 'State Bank of India Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/SBI.png'),
            array('id' => '190','bankid' => '209','bankcode' => 'SCCC','bankname' => 'Standard Chartered Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Standard%20Chartered%20Bank.jpg'),
            array('id' => '191','bankid' => '210','bankcode' => 'UTCC','bankname' => 'UTI Axis Bank Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/uti-axis-bank.jpg'),
            array('id' => '192','bankid' => '211','bankcode' => 'VICC','bankname' => 'Vijaya Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/vijaya-bank.png'),
            array('id' => '193','bankid' => '212','bankcode' => 'AMEX','bankname' => 'American Express Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Bank-Of-America-Logo-600x304.png'),
            array('id' => '194','bankid' => '213','bankcode' => 'JANA','bankname' => 'Janaseva Sahakari Bank','masterifsc' => 'JANA0000001','url' => 'http://uat.mahagram.in/banklogo/Janaseva%20Sahakari%20Bank.jpg'),
            array('id' => '195','bankid' => '214','bankcode' => 'KAIJ','bankname' => 'Kallapana Ichalkaranji Awade Janaseva Sahakari Ban','masterifsc' => 'KAIJ0000001','url' => 'http://uat.mahagram.in/banklogo/Kallapanna-Awade-Ichalkaranji-Janata-Sahakari.jpg'),
            array('id' => '196','bankid' => '215','bankcode' => 'ICIP','bankname' => 'Pandharpur Merchant Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Pandharpur%20Merchant%20Co-Op%20Bank.jpg'),
            array('id' => '197','bankid' => '216','bankcode' => 'HDGB','bankname' => 'Gayatri Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Gayatri%20Bank.jpg'),
            array('id' => '198','bankid' => '217','bankcode' => 'HDFP','bankname' => 'Pochampally Co-Op Urban Bank','masterifsc' => 'YESB0PCUB01','url' => 'http://uat.mahagram.in/banklogo/Pochampally%20Co-Op%20Urban%20Bank.jpg'),
            array('id' => '199','bankid' => '218','bankcode' => 'HDFA','bankname' => 'Dr. Annasaheb Chougule Urban Co-Op Bank','masterifsc' => 'NULL','url' => NULL),
            array('id' => '200','bankid' => '219','bankcode' => 'SDCB','bankname' => 'Surat District Co-Op Bank','masterifsc' => 'SDCB0000001','url' => 'http://uat.mahagram.in/banklogo/Surat%20District%20Co-Op%20Bank.jpg'),
            array('id' => '201','bankid' => '220','bankcode' => 'HDFS','bankname' => 'Suco Souharda Sahakari Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Suco%20Souharda%20Sahakari%20Bank.png'),
            array('id' => '202','bankid' => '221','bankcode' => 'IBKP','bankname' => 'Pune Peoples Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Pune%20Peoples%20Co-Op%20Bank.png'),
            array('id' => '203','bankid' => '223','bankcode' => 'KKBN','bankname' => 'National Co-Op Bank','masterifsc' => 'UTIB0SNCB01','url' => 'http://uat.mahagram.in/banklogo/National%20Co-Op%20Bank.png'),
            array('id' => '204','bankid' => '224','bankcode' => 'HDPA','bankname' => 'Parshwanath Co-Op Bank','masterifsc' => 'HDFC0CPCB01','url' => 'http://uat.mahagram.in/banklogo/Parshwanath Co-Op Bank.jpg'),
            array('id' => '205','bankid' => '225','bankcode' => 'ASBL','bankname' => 'Apna Sahakari Bank','masterifsc' => 'ASBL0000001','url' => 'http://uat.mahagram.in/banklogo/Apna%20Sahakari%20Bank.jpg'),
            array('id' => '206','bankid' => '226','bankcode' => 'HDJC','bankname' => 'Jalore Nagrik Sahakari Bank','masterifsc' => 'HDFC0CJALOR','url' => 'http://uat.mahagram.in/banklogo/Jalgaon%20Peoples%20Co-Op%20Bank.jpg'),
            array('id' => '207','bankid' => '227','bankcode' => 'VARA','bankname' => 'Varachha Co-Op Bank','masterifsc' => 'VARA0000001','url' => 'http://uat.mahagram.in/banklogo/Varachha%20Co-Op%20Bank.png'),
            array('id' => '208','bankid' => '228','bankcode' => 'HDFJ','bankname' => 'Janata Co-Op Bank, Malegaon','masterifsc' => 'NULL','url' => NULL),
            array('id' => '209','bankid' => '229','bankcode' => 'ICIS','bankname' => 'Shri Basaveshwar Sahakari Bank Niyamit Bagalkot','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Shri-Basaveshwar-Sahakari-Bank.jpg'),
            array('id' => '210','bankid' => '230','bankcode' => 'KKBS','bankname' => 'Shirpur Peoples Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Shirpur%20Peoples%20Co-Op%20Bank.jpg'),
            array('id' => '211','bankid' => '231','bankcode' => 'BMBL','bankname' => 'Bhartiya Mahila Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Bhartiya%20Mahila%20Bank.jpg'),
            array('id' => '212','bankid' => '232','bankcode' => 'KLGB','bankname' => 'Kerala Gramin Bank','masterifsc' => 'KLGB0040101','url' => 'http://uat.mahagram.in/banklogo/Kerala%20Gramin%20Bank.png'),
            array('id' => '213','bankid' => '233','bankcode' => 'PKGB','bankname' => 'Pragathi Krishna Gramin Bank','masterifsc' => 'PKGB0010500','url' => 'http://uat.mahagram.in/banklogo/Pragathi-Krishna-Gramin-Bank.jpg'),
            array('id' => '214','bankid' => '234','bankcode' => 'YESP','bankname' => 'Yadagiri Lakshmi Narasimha Swamy Co-Op Urban Bank','masterifsc' => 'YESB0YLNS01','url' => 'http://uat.mahagram.in/banklogo/Yadagiri%20Lakshmi%20Narasimha%20Swamy.png'),
            array('id' => '215','bankid' => '235','bankcode' => 'ICIH','bankname' => 'Hutatma Sahakari Bank','masterifsc' => 'ICIC00HSBLW','url' => 'http://uat.mahagram.in/banklogo/Hutatma%20Sahakari%20Bank.jpg'),
            array('id' => '216','bankid' => '236','bankcode' => 'HPSC','bankname' => 'Himachal Pradesh State Co-Op Bank','masterifsc' => 'HPSC0000051','url' => 'http://uat.mahagram.in/banklogo/Himachal%20Pradesh%20State%20Co-Op%20Bank.png'),
            array('id' => '217','bankid' => '237','bankcode' => 'ICIA','bankname' => 'Adarsh Urban Co-Op Bank, Hyderabad','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Adarsh%20Urban%20Co-Op%20Bank.png'),
            array('id' => '218','bankid' => '238','bankcode' => 'ICIM','bankname' => 'Mayani Urban Co-Op Bank','masterifsc' => 'ICIC00TMUCB','url' => NULL),
            array('id' => '219','bankid' => '239','bankcode' => 'ICPU','bankname' => 'Pandharpur Urban Co-Op Bank','masterifsc' => 'PUCB0000001','url' => 'http://uat.mahagram.in/banklogo/Pandharpur%20Urban%20Co-Op%20Bank.png'),
            array('id' => '220','bankid' => '240','bankcode' => 'SVAG','bankname' => 'Vananchal Gramin Bank','masterifsc' => 'SBIN0RRVCGB','url' => 'http://uat.mahagram.in/banklogo/Vananchal%20Gramin%20Bank.png'),
            array('id' => '221','bankid' => '241','bankcode' => 'PPGB','bankname' => 'Punjab Gramin Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Punjab%20Gramin%20Bank.png'),
            array('id' => '222','bankid' => '242','bankcode' => 'CVCB','bankname' => 'Shree Veershaiv Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Shree%20Veershaiv%20Co-Op%20Bank.jpg'),
            array('id' => '223','bankid' => '243','bankcode' => 'TDCB','bankname' => 'Thrissur District Central Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Thrissur%20District%20Central%20Co-Op.png'),
            array('id' => '224','bankid' => '244','bankcode' => 'VSBL','bankname' => 'Vishweshwar Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Vishweshwar%20Co-Op%20Bank.png'),
            array('id' => '225','bankid' => '245','bankcode' => 'HDRU','bankname' => 'Raipur Urban Mercantile Co-Op Bank','masterifsc' => 'HDFC0CTRUMC','url' => 'http://uat.mahagram.in/banklogo/Raipur%20Urban%20Mercantile%20Co-Op.png'),
            array('id' => '226','bankid' => '246','bankcode' => 'ICZS','bankname' => 'Zila Sahkari Bank','masterifsc' => 'ICIC00BDCCB','url' => 'http://uat.mahagram.in/banklogo/Zila%20Sahkari%20Bank.png'),
            array('id' => '227','bankid' => '247','bankcode' => 'SBIT','bankname' => 'Titwala','masterifsc' => 'NULL','url' => NULL),
            array('id' => '228','bankid' => '248','bankcode' => 'SBDO','bankname' => 'Dombivli East','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Dombivli%20Nagari%20Sahakari%20Bank.jpg'),
            array('id' => '229','bankid' => '250','bankcode' => 'WBMG','bankname' => 'MGCB Main','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/MGCB%20Main.png'),
            array('id' => '230','bankid' => '251','bankcode' => 'HDSI','bankname' => 'Sindhudurg District Central Co-Op Bank','masterifsc' => 'IBKL0726SCB','url' => 'http://uat.mahagram.in/banklogo/Sindhudurg District Central Co-Op Bank.png'),
            array('id' => '231','bankid' => '252','bankcode' => 'ICMA','bankname' => 'Hamirpur District Co-Op Bank, Mahoba','masterifsc' => 'ICIC00HDCCB','url' => NULL),
            array('id' => '232','bankid' => '253','bankcode' => 'SMCB','bankname' => 'Shivalik Mercantile Co-Op Bank','masterifsc' => 'SMCB0001000','url' => 'http://uat.mahagram.in/banklogo/Shivalik%20Mercantile%20Co-Op%20Bank.png'),
            array('id' => '233','bankid' => '254','bankcode' => 'HCBL','bankname' => 'Hasti Co-Op Bank','masterifsc' => 'HCBL0000101','url' => 'http://uat.mahagram.in/banklogo/Hasti%20Co-Op%20Bank.png'),
            array('id' => '234','bankid' => '255','bankcode' => 'RSBL','bankname' => 'Rajgurunagar Sahakari Bank','masterifsc' => 'RSBL0000002','url' => 'http://uat.mahagram.in/banklogo/Rajgurunagar%20Sahakari%20Bank.png'),
            array('id' => '235','bankid' => '256','bankcode' => 'BDBL','bankname' => 'Bandhan Bank','masterifsc' => 'BDBL0001000','url' => 'http://uat.mahagram.in/banklogo/Bandhan%20Bank.jpg'),
            array('id' => '236','bankid' => '257','bankcode' => 'IBDU','bankname' => 'Dapoli Urban Co-Op Bank','masterifsc' => 'IBKL0116DPC','url' => NULL),
            array('id' => '237','bankid' => '258','bankcode' => 'GSCB','bankname' => 'Gujarat State Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Gujarat%20State%20Co-Op%20Bank.png'),
            array('id' => '238','bankid' => '259','bankcode' => 'MUBL','bankname' => 'Municipal Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Municipal%20Co-Op%20Bank.jpg'),
            array('id' => '239','bankid' => '260','bankcode' => 'ICRU','bankname' => 'Rajapur Urban Co-Op Bank','masterifsc' => 'ICIC00RUCBL','url' => 'http://uat.mahagram.in/banklogo/Rajapur%20Urban%20Co-Op%20Bank.png'),
            array('id' => '240','bankid' => '261','bankcode' => 'GSAD','bankname' => 'Ahmedabad District Central Co-Op Bank','masterifsc' => 'KKBK0MVCB01','url' => 'http://uat.mahagram.in/banklogo/Ahmedabad%20District%20Central%20Co-Op.png'),
            array('id' => '241','bankid' => '262','bankcode' => 'IDFB','bankname' => 'IDFC Bank','masterifsc' => 'IDFB0010201','url' => 'http://uat.mahagram.in/banklogo/IDFC%20Bank.jpg'),
            array('id' => '242','bankid' => '263','bankcode' => 'SBRM','bankname' => 'Rajasthan Marudhara Gramin Bank','masterifsc' => 'SBBJ0RRMRGB','url' => 'http://uat.mahagram.in/banklogo/Rajasthan%20Marudhara%20Gramin%20Bank.jpg'),
            array('id' => '243','bankid' => '264','bankcode' => 'SUSB','bankname' => 'Suvarnayug Sahakari Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Suvarnayug%20Sahakari%20Bank.jpg'),
            array('id' => '244','bankid' => '265','bankcode' => 'SUCO','bankname' => 'Sutex Co-Op Bank','masterifsc' => 'SUTB0000001','url' => 'http://uat.mahagram.in/banklogo/Sutex%20Co-Op%20Bank.jpg'),
            array('id' => '245','bankid' => '266','bankcode' => 'NASB','bankname' => 'Nagar Sahkari Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Kurmanchal%20Nagar%20Sahkari%20Bank%20Ltd.jpg'),
            array('id' => '246','bankid' => '267','bankcode' => 'IRTO','bankname' => 'Irinjalakuda Town Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Irinjalakuda%20Town%20Co-Op%20Bank.png'),
            array('id' => '247','bankid' => '268','bankcode' => 'SHBH','bankname' => 'Shivajirao Bhosale Sahakari Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Shivajirao%20Bhosale%20Sahakari%20Bank.png'),
            array('id' => '248','bankid' => '269','bankcode' => 'TBSB','bankname' => 'Thane Bharat Sahakari Bank','masterifsc' => 'TBSB0000001','url' => 'http://uat.mahagram.in/banklogo/Thane%20Bharat%20Sahakari%20Bank.jpg'),
            array('id' => '249','bankid' => '270','bankcode' => 'MCOB','bankname' => 'Maratha Co-Op Bank','masterifsc' => 'IBKL0101MCB','url' => 'http://uat.mahagram.in/banklogo/Maratha%20Co-Op%20Bank.jpg'),
            array('id' => '250','bankid' => '271','bankcode' => 'IBJS','bankname' => 'Pithoragarh Jila Sahkari Bank','masterifsc' => 'IBKL0768PJS','url' => 'http://uat.mahagram.in/banklogo/Pithoragarh Jila Sahkari Bank.jpg'),
            array('id' => '251','bankid' => '272','bankcode' => 'PCSB','bankname' => 'Pune Cantonment Sahakari Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Pune%20Cantonment%20Sahakari%20Bank.png'),
            array('id' => '252','bankid' => '274','bankcode' => 'MASB','bankname' => 'Malad Sahkari Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Malad%20Sahkari%20Bank.jpg'),
            array('id' => '253','bankid' => '275','bankcode' => 'SML','bankname' => 'Shree Mahalaxmi Co-Op Bank','masterifsc' => 'SVCB0012003','url' => 'http://uat.mahagram.in/banklogo/Shree%20Mahalaxmi%20Co-Op%20Bank.jpg'),
            array('id' => '254','bankid' => '276','bankcode' => 'MZSB','bankname' => 'Moradabad Zila Sahkari Bank','masterifsc' => 'IBKL0122SBM','url' => 'http://uat.mahagram.in/banklogo/Moradabad%20Zila%20Sahkari%20Bank.png'),
            array('id' => '255','bankid' => '277','bankcode' => 'SCCB','bankname' => 'Siwan Central Co-Op Bank','masterifsc' => 'NULL','url' => NULL),
            array('id' => '256','bankid' => '278','bankcode' => 'MGBS','bankname' => 'Madhyanchal Gramin Bank, Sagar','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Madhyanchal%20Gramin%20Bank.jpg'),
            array('id' => '257','bankid' => '279','bankcode' => 'TKGB','bankname' => 'Triveni Kshetriya Gramin Bank','masterifsc' => 'NULL','url' => NULL),
            array('id' => '258','bankid' => '280','bankcode' => 'RBCC','bankname' => 'RBL Bank Credit Card','masterifsc' => 'RATN0000001','url' => 'http://uat.mahagram.in/banklogo/RBL Bank.png'),
            array('id' => '259','bankid' => '281','bankcode' => 'PBCC','bankname' => 'Punjab National Bank Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Punjab%20National%20Bank.png'),
            array('id' => '260','bankid' => '283','bankcode' => 'IBCC','bankname' => 'IndusInd Bank Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/IndusInd%20Bank.png'),
            array('id' => '261','bankid' => '284','bankcode' => 'CBCC','bankname' => 'Canara Bank Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Canara%20Bank.png'),
            array('id' => '262','bankid' => '285','bankcode' => 'IDCC','bankname' => 'IDBI Bank Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/IDBI%20bank.png'),
            array('id' => '263','bankid' => '286','bankcode' => 'ANCC','bankname' => 'Andhra Bank Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Andhra%20Bank.jpg'),
            array('id' => '264','bankid' => '287','bankcode' => 'BKCC','bankname' => 'Bank Of India Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/BANK-OF-INDIA-LOGO.png'),
            array('id' => '265','bankid' => '288','bankcode' => 'BABC','bankname' => 'Bank Of Baroda Credit Card','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/bank-of-baroda.png'),
            array('id' => '266','bankid' => '289','bankcode' => 'IOGB','bankname' => 'Odisha Gramya Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Odisha%20Gramya%20Bank.png'),
            array('id' => '267','bankid' => '290','bankcode' => 'UMSC','bankname' => 'Udaipur Mahila Samrudhi Urban Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Udaipur%20Mahila%20Samrudhi%20Urban%20Co.png'),
            array('id' => '268','bankid' => '291','bankcode' => 'DSCB','bankname' => 'Delhi State Co-Op Bank','masterifsc' => 'DLSC0000001','url' => 'http://uat.mahagram.in/banklogo/Delhi%20State%20Co-Op%20Bank.png'),
            array('id' => '269','bankid' => '292','bankcode' => 'COBL','bankname' => 'Citizen Co-Op Bank, Noida','masterifsc' => 'ICIC00CCOBL','url' => 'http://uat.mahagram.in/banklogo/Citizen%20Co-Op%20Bank,%20Noida.png'),
            array('id' => '270','bankid' => '293','bankcode' => 'CUCB','bankname' => 'Chikhli Urban Co-Op Bank','masterifsc' => 'YESB0CCUB01','url' => 'http://uat.mahagram.in/banklogo/Chikhli%20Urban%20Co-Op%20Bank.png'),
            array('id' => '271','bankid' => '294','bankcode' => 'PNSB','bankname' => 'Poornawadi Nagrik Sahakari Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Poornawadi%20Nagrik%20Sahakari%20Bank.png'),
            array('id' => '272','bankid' => '295','bankcode' => 'AGBL','bankname' => 'Ahmednagar Mer Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Ahmednagar%20Mer%20Co-Op%20Bank.png'),
            array('id' => '273','bankid' => '296','bankcode' => 'PSBL','bankname' => 'Pavana Sahakari Bank','masterifsc' => 'IBKL0087PSB','url' => 'http://uat.mahagram.in/banklogo/Pavana%20Sahakari%20Bank.png'),
            array('id' => '274','bankid' => '297','bankcode' => 'UCBL','bankname' => 'Urban Co-Op Bank','masterifsc' => 'KKBK0UCBL02','url' => NULL),
            array('id' => '275','bankid' => '298','bankcode' => 'AIRP','bankname' => 'Airtel Payments Bank','masterifsc' => 'AIRP0000001','url' => 'http://uat.mahagram.in/banklogo/Airtel%20Payments%20Bank.png'),
            array('id' => '276','bankid' => '299','bankcode' => 'JPCB','bankname' => 'Jalgaon Peoples Co-Op Bank','masterifsc' => 'JPCB0000001','url' => 'http://uat.mahagram.in/banklogo/Jalgaon%20Peoples%20Co-Op%20Bank.jpg'),
            array('id' => '277','bankid' => '300','bankcode' => 'VVSB','bankname' => 'Vasai Vikas Co-op Bank','masterifsc' => 'VVSB0000001','url' => 'http://uat.mahagram.in/banklogo/Vasai%20Vikas%20Co-op%20Bank.png'),
            array('id' => '278','bankid' => '301','bankcode' => 'ESFB','bankname' => 'Equitas Small Finance Bank','masterifsc' => 'ESFB0000002','url' => 'http://uat.mahagram.in/banklogo/Equitas%20Small%20Finance%20Bank.png'),
            array('id' => '279','bankid' => '302','bankcode' => 'NCBL','bankname' => 'Noble Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Noble%20Co-Op%20Bank.jpg'),
            array('id' => '280','bankid' => '303','bankcode' => 'JDCB','bankname' => 'Jalaun District Co-Op Bank','masterifsc' => 'ICIC00JDCBL','url' => NULL),
            array('id' => '281','bankid' => '304','bankcode' => 'VUCB','bankname' => 'Vaidyanath Urban Co-Op Bank','masterifsc' => 'HDFC0CVUCBL','url' => 'http://uat.mahagram.in/banklogo/Vaidyanath%20Urban%20Co-Op%20Bank.jpg'),
            array('id' => '282','bankid' => '305','bankcode' => 'SGCB','bankname' => 'Sapthagiri Grameena Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Sapthagiri%20Grameena%20Bank.png'),
            array('id' => '283','bankid' => '306','bankcode' => 'AJHB','bankname' => 'Ambarnath Jai Hind Co-Op Bank','masterifsc' => 'ICIC00AJHCB','url' => 'http://uat.mahagram.in/banklogo/Ambarnath%20Jai%20Hind%20Co-Op%20Bank.png'),
            array('id' => '284','bankid' => '307','bankcode' => 'SVBL','bankname' => 'Seva Vikas Co-Op Bank','masterifsc' => 'SVBL0000001','url' => 'http://uat.mahagram.in/banklogo/Seva%20Vikas%20Co-Op%20Bank.jpg'),
            array('id' => '285','bankid' => '308','bankcode' => 'PPCB','bankname' => 'Pachora Peoples Co-Op Bank','masterifsc' => 'HDFC0CPPCB1','url' => NULL),
            array('id' => '286','bankid' => '309','bankcode' => 'IIPB','bankname' => 'India Post Payments Bank','masterifsc' => 'IPOS0000001','url' => 'http://uat.mahagram.in/banklogo/India%20Post%20Payments%20Bank.png'),
            array('id' => '287','bankid' => '310','bankcode' => 'BMCL','bankname' => 'Bombay Mercantile Co-Op Bank','masterifsc' => 'UTIB0SBMCB1','url' => 'http://uat.mahagram.in/banklogo/Bombay%20Mercantile%20Co-Op%20Bank.jpg'),
            array('id' => '288','bankid' => '311','bankcode' => 'MDCB','bankname' => 'Malda District Central Co-Op Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Malda%20District%20Central%20Co-Op%20Bank.png'),
            array('id' => '289','bankid' => '312','bankcode' => 'UJVN','bankname' => 'Ujjivan Small Finance Bank','masterifsc' => 'UJVN0003524','url' => 'http://uat.mahagram.in/banklogo/Ujjivan%20Small%20Finance%20Bank.jpg'),
            array('id' => '290','bankid' => '313','bankcode' => 'JCBL','bankname' => 'Jamia Co-Op Bank','masterifsc' => 'UTIB0SJCB03','url' => 'http://uat.mahagram.in/banklogo/Jamia Co-Op Bank.jpg'),
            array('id' => '291','bankid' => '314','bankcode' => 'IUCB','bankname' => 'Integral Urban Co-Op Bank','masterifsc' => 'HDFC0CIUCBL','url' => 'http://uat.mahagram.in/banklogo/Integral%20Urban%20Co-Op%20Bank.png'),
            array('id' => '292','bankid' => '315','bankcode' => 'ESMF','bankname' => 'ESAF Small Finance Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/ESAF%20Small%20Finance%20Bank.png'),
            array('id' => '293','bankid' => '316','bankcode' => 'MGCB','bankname' => 'Mogaveera Co-Op Bank','masterifsc' => 'IBKL0452MCB','url' => 'http://uat.mahagram.in/banklogo/Mogaveera%20Co-Op%20Bank.jpg'),
            array('id' => '294','bankid' => '317','bankcode' => 'AACB','bankname' => 'Akhand Anand┬áCo-Op Bank','masterifsc' => 'HDFC0CAACOB','url' => 'http://uat.mahagram.in/banklogo/Akhand Anand┬áCo-Op Bank.png'),
            array('id' => '295','bankid' => '318','bankcode' => 'SBPP','bankname' => 'Sardar Bhiladwala Pardi Peoples Co-Op Bank','masterifsc' => 'UTIB0SBPP12','url' => 'http://uat.mahagram.in/banklogo/Sardar%20Bhiladwala%20Pardi%20Peoples.png'),
            array('id' => '296','bankid' => '319','bankcode' => 'MPSS','bankname' => 'Manvi Pattana Souharda Sahakari Bank','masterifsc' => 'HDFC0CMPS01','url' => 'http://uat.mahagram.in/banklogo/Manvi%20Pattana%20Souharda%20Sahakari.png'),
            array('id' => '297','bankid' => '320','bankcode' => 'SSSB','bankname' => 'Shree Sharada Sahakari Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Shree%20Sharada%20Sahakari%20Bank.jpg'),
            array('id' => '298','bankid' => '321','bankcode' => 'ASML','bankname' => 'Aircel Smart Money Ltd','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Aircel%20Smart%20Money%20Ltd.jpg'),
            array('id' => '299','bankid' => '322','bankcode' => 'DCCL','bankname' => 'Mumbai District Central Co-Operative Bank Ltd','masterifsc' => 'MDCB0680001','url' => 'http://uat.mahagram.in/banklogo/Mumbai%20District%20Central%20Co-Operative%20B.png'),
            array('id' => '300','bankid' => '323','bankcode' => 'TCCB','bankname' => 'The Thane District Central Co-Operative Bank Ltd','masterifsc' => 'TDCB0000001','url' => 'http://uat.mahagram.in/banklogo/The%20Thane%20District%20Central%20Co-Op.jpg'),
            array('id' => '301','bankid' => '324','bankcode' => 'ZCBL','bankname' => 'The Zoroastrian Cooperative Bank Limited','masterifsc' => 'ZCBL0000001','url' => 'http://uat.mahagram.in/banklogo/The%20Zoroastrian%20Cooperative%20Bank.jpg'),
            array('id' => '302','bankid' => '325','bankcode' => 'SSCB','bankname' => 'The Saurashtra Cooperative Bank Ltd','masterifsc' => 'GSCB0USAURA','url' => 'http://uat.mahagram.in/banklogo/The%20Saurashtra%20Cooperative%20Bank.png'),
            array('id' => '303','bankid' => '326','bankcode' => 'KNSB','bankname' => 'Kurmanchal Nagar Sahkari Bank Ltd','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Kurmanchal%20Nagar%20Sahkari%20Bank%20Ltd.jpg'),
            array('id' => '304','bankid' => '327','bankcode' => 'SURY','bankname' => 'Suryoday Small Finance Bank','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Suryoday%20Small%20Finance%20Bank.png'),
            array('id' => '305','bankid' => '328','bankcode' => 'AKJB','bankname' => 'Akola Janata Commercial Co Operative Bank Ltd','masterifsc' => 'AKJB0000001','url' => 'http://uat.mahagram.in/banklogo/Akola%20Janata%20Commercial%20Co%20Operative.png'),
            array('id' => '306','bankid' => '329','bankcode' => 'SAHE','bankname' => 'THE SAHEBRAO DESHMUKH CO-OP. BANK LTD','masterifsc' => 'SAHE0000001','url' => 'http://uat.mahagram.in/banklogo/THE%20SAHEBRAO%20DESHMUKH%20CO-OP.jpg'),
            array('id' => '307','bankid' => '330','bankcode' => 'CRUB','bankname' => 'Shri Chhatrapati Rajarshi Shahu Urban Co-Op Bank L','masterifsc' => 'CRUB0000001','url' => 'http://uat.mahagram.in/banklogo/Shri%20Chhatrapati%20Rajarshi%20Shahu.jpg'),
            array('id' => '308','bankid' => '331','bankcode' => 'ADCC','bankname' => 'Akola District Central Co-operative Bank','masterifsc' => 'ADCC0000001','url' => 'http://uat.mahagram.in/banklogo/Akola District Central Co-operative Bank.jpg'),
            array('id' => '309','bankid' => '332','bankcode' => 'THCB','bankname' => 'The Hindusthan Co-operative Bank Ltd.','masterifsc' => 'SVCB0001020','url' => 'http://uat.mahagram.in/banklogo/The%20Hindusthan%20Co-operative%20Bank.jpg'),
            array('id' => '310','bankid' => '333','bankcode' => 'SSBL','bankname' => 'Sadhana Sahakari Bank Ltd','masterifsc' => 'IBKL0041SB1','url' => 'http://uat.mahagram.in/banklogo/Sadhana%20Sahakari%20Bank%20Ltd.png'),
            array('id' => '311','bankid' => '334','bankcode' => 'SDCC','bankname' => 'The Sabarkantha District Central Cooperative Bank ','masterifsc' => 'GSCB0SKB001','url' => 'http://uat.mahagram.in/banklogo/The%20Sabarkantha%20District%20Central.png'),
            array('id' => '312','bankid' => '335','bankcode' => 'SSBM','bankname' => 'Sharad Sahakari Bank Ltd. Manchar','masterifsc' => 'HDFC0CSHSBL','url' => 'http://uat.mahagram.in/banklogo/Sharad%20Sahakari%20Bank%20Ltd.png'),
            array('id' => '313','bankid' => '336','bankcode' => 'UUCB','bankname' => 'Udaipur urban Co-operative bank Ltd','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/Udaipur%20urban%20Co-operative%20bank.png'),
            array('id' => '314','bankid' => '337','bankcode' => 'VSCB','bankname' => 'Vikas Souharda Co-operative Bank Limited','masterifsc' => 'HDFC0CVIKAS','url' => 'http://uat.mahagram.in/banklogo/Vikas%20Souharda%20Co-operative%20Bank.png'),
            array('id' => '315','bankid' => '338','bankcode' => 'PNSL','bankname' => 'Priyadarshani Nagari Sahakari Bank','masterifsc' => 'KKBK0PNSB01','url' => 'http://uat.mahagram.in/banklogo/Priyadarshani%20Nagari%20Sahakari%20Bank.jpg'),
            array('id' => '316','bankid' => '339','bankcode' => 'KAIB','bankname' => 'The Kaira District Central Cooperative Bank Ltd','masterifsc' => 'ICIC00KAIRA','url' => 'http://uat.mahagram.in/banklogo/The%20Kaira%20District%20Central%20Cooperat.png'),
            array('id' => '317','bankid' => '340','bankcode' => 'MCCB','bankname' => 'The Murshidabad District Central Co Operative Bank','masterifsc' => 'NULL','url' => NULL),
            array('id' => '318','bankid' => '341','bankcode' => 'KCUB','bankname' => 'Kottayam Co-operative Urban bank Ltd','masterifsc' => 'IBKL0027K01','url' => 'http://uat.mahagram.in/banklogo/Kottayam%20Co-operative%20Urban%20bank.jpg'),
            array('id' => '319','bankid' => '342','bankcode' => 'PUCB','bankname' => 'The Panipat Urban Co-operative Bank Ltd','masterifsc' => 'UTIB0PCCB01','url' => 'http://uat.mahagram.in/banklogo/The%20Panipat%20Urban%20Co-operative.jpg'),
            array('id' => '320','bankid' => '343','bankcode' => 'TSAB','bankname' => 'Telangana State Cooperative Apex Bank','masterifsc' => 'APBL0000138','url' => 'http://uat.mahagram.in/banklogo/Telangana%20State%20Cooperative%20Apex.jpg'),
            array('id' => '321','bankid' => '344','bankcode' => 'ACAB','bankname' => 'The Assam Coop Apex Bank Ltd','masterifsc' => 'NULL','url' => 'http://uat.mahagram.in/banklogo/The%20Assam%20Coop%20Apex%20Bank%20Ltd.png'),
            array('id' => '323','bankid' => '346','bankcode' => 'SUNB','bankname' => 'Surat National Co-op Bank','masterifsc' => 'SUNB0000001','url' => 'http://uat.mahagram.in/banklogo/Surat%20National%20Co-op%20Bank.png'),
            array('id' => '324','bankid' => '347','bankcode' => 'FINO','bankname' => 'FINO Payment Bank','masterifsc' => 'ICIC00FINPY','url' => 'http://uat.mahagram.in/banklogo/FINO%20Payment%20Bank.jpg'),
            array('id' => '325','bankid' => '348','bankcode' => 'MRGB','bankname' => 'Narmada Malwa Gramin Bank','masterifsc' => 'BKID0NAMRGB','url' => 'http://uat.mahagram.in/banklogo/Narmada%20Malwa%20Gramin%20Bank.jpg'),
            array('id' => '326','bankid' => '349','bankcode' => 'MSBL','bankname' => 'Markandey Nagari Sahakari Bank Ltd','masterifsc' => 'ICIC00MNSBL','url' => NULL),
            array('id' => '327','bankid' => '350','bankcode' => 'BCBL','bankname' => 'The Bijnor Urban Co-Operative Bank','masterifsc' => 'NULL','url' => NULL),
            array('id' => '328','bankid' => '351','bankcode' => 'SYU	','bankname' => 'Syndicate Bank ','masterifsc' => 'SYNB0000100','url' => 'http://uat.mahagram.in/banklogo/Syndicate%20Bank.jpg')
          );
          foreach ($mahabanks as &$mahabank) {
            unset($mahabank['id']);
        }
          \App\Models\Mahabank::insert($mahabanks);

    }
}
